### PR TITLE
updates

### PR DESCRIPTION
**Pull request by ryanlabar**
Synthetic data box is now configurable.

Added an ability to have some boxes checked, and reflect in the README.

Allow using logos instead of/together with textual names in the legend

Added the AIIA logo to bottom right corner

### CODE REVIEW

**Comment by mariyadavydova** [comment]
* Synthetic data box is now configurable. - DONE
* Allow using logos instead of/together with textual names in the legend. - DONE
* Added the AIIA logo to bottom right corner. - DONE

* Added an ability to have some boxes checked, and reflect in the README. - not really done
I meant that if the checkboxes are checked, the corresponding boxes should be colored. Compare the two screenshots below: first is the page just loaded, and second after I uncheck the checkbox and check it again. 

Screenshot 2021-12-15 at 02 08 25

Screenshot 2021-12-15 at 02 08 36

* The bug with the legend scaling is still there (I use Chrome).

Screenshot 2021-12-15 at 02 15 04

**Review by mariyadavydova — CHANGES_REQUESTED** [review]
Please fix the issues listed in a previous comment

**Comment by ryanlabar** [comment]
Are you running this local? This should be working as expected. It seems like your css and JS aren't updated for you--could be a caching issue? Let me know if this is not the case. @mariyadavydova

**Comment by mariyadavydova** [comment]
@ryanlabar You are right, the problem with the pre-checked boxes is fixed, it was caching.

I use https://ai-infrastructure-alliance.github.io/blueprints/interactive-stack-diagram/stack.html for the test, it is connected to this branch ATM.

What about scaling the legend? The problem is still reproduced, even in incognito mode.

**Comment by mariyadavydova** [comment]
Actually, let me merge this update, because it's really cool, and I'll add an issue about the legend scaling.

**Pull request merged**
